// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6BZHZjgdjOnSLEqeN5DdxtK8uOAVKpM',
    appId: '1:749919368521:web:b2f2a405deb921fb2d5698',
    messagingSenderId: '749919368521',
    projectId: 'ola-car-app',
    authDomain: 'ola-car-app.firebaseapp.com',
    storageBucket: 'ola-car-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA1g9yHrKv1WVMa4zDl6TzHMGJsJlnfFs',
    appId: '1:749919368521:android:ca0804c82d83093d2d5698',
    messagingSenderId: '749919368521',
    projectId: 'ola-car-app',
    storageBucket: 'ola-car-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRY3Y5QJY4cyGzJ3DhHRbMcEQo2HvH0U',
    appId: '1:749919368521:ios:eba93e6788e8dd932d5698',
    messagingSenderId: '749919368521',
    projectId: 'ola-car-app',
    storageBucket: 'ola-car-app.firebasestorage.app',
    iosBundleId: 'com.example.olaApp1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRY3Y5QJY4cyGzJ3DhHRbMcEQo2HvH0U',
    appId: '1:749919368521:ios:eba93e6788e8dd932d5698',
    messagingSenderId: '749919368521',
    projectId: 'ola-car-app',
    storageBucket: 'ola-car-app.firebasestorage.app',
    iosBundleId: 'com.example.olaApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL6BZHZjgdjOnSLEqeN5DdxtK8uOAVKpM',
    appId: '1:749919368521:web:aee26398e4ebc23e2d5698',
    messagingSenderId: '749919368521',
    projectId: 'ola-car-app',
    authDomain: 'ola-car-app.firebaseapp.com',
    storageBucket: 'ola-car-app.firebasestorage.app',
  );
}
